#!/bin/bash
#SBATCH --job-name=llm-all-papers
#SBATCH --partition=kisski
#SBATCH -G A100:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=40G
#SBATCH --time=04:00:00
#SBATCH --output=all_papers_%A_%a.log
#SBATCH --error=all_papers_%A_%a.err
#SBATCH -C inet

# Run extraction on ALL papers in papers_list.txt for ONE model.
#
# Usage:
#   sbatch --array=0-70 grete/jobs/grete_extract_all_papers.sh <model_id>
#
# Example (one model, all 71 papers):
#   sbatch --array=0-70 grete/jobs/grete_extract_all_papers.sh meta-llama/Llama-3.2-1B-Instruct
#
# To submit all 8 models, run the helper script:
#   bash grete/jobs/submit_all_models.sh

MODEL_ID="${1:-meta-llama/Llama-3.2-1B-Instruct}"

# Read ArXiv IDs from papers_ids.txt (one per line, generated by setup_papers_list.sh)
PAPERS_FILE="$HOME/llm-extraction/data/gold_standard/papers_ids.txt"

if [ ! -f "$PAPERS_FILE" ]; then
    echo "ERROR: $PAPERS_FILE not found. Run setup_papers_list.sh first."
    exit 1
fi

# Get the ArXiv ID for this array task (0-indexed)
ARXIV_ID=$(sed -n "$((SLURM_ARRAY_TASK_ID + 1))p" "$PAPERS_FILE")

if [ -z "$ARXIV_ID" ]; then
    echo "ERROR: No ArXiv ID found at index $SLURM_ARRAY_TASK_ID in $PAPERS_FILE"
    exit 1
fi

echo "=========================================="
echo "Extraction Job on Grete (All Papers)"
echo "=========================================="
echo "Job ID:       $SLURM_JOB_ID"
echo "Array Task:   $SLURM_ARRAY_TASK_ID / 70"
echo "ArXiv ID:     $ARXIV_ID"
echo "Model:        $MODEL_ID"
echo "Node:         $SLURMD_NODENAME"
echo "GPU:          $CUDA_VISIBLE_DEVICES"
echo "=========================================="

# Load miniforge3 module
module load miniforge3

# Initialize and activate conda environment
eval "$(conda shell.bash hook)"
conda activate /mnt/vast-kisski/home/alaa.kefi/u25486/llm-extraction/llm-env

# Navigate to project
cd ~/llm-extraction

# Hugging Face cache on project space (not HOME) to avoid quota
export HF_HOME="${PROJECT_DIR:-/projects/extern/kisski/kisski-tib-llms4subjects/dir.project}/.cache/huggingface"
mkdir -p "$HF_HOME"

# Hugging Face token for gated models (Llama, etc.)
if [ -f "$HOME/.hf_token" ]; then
  export HUGGING_FACE_HUB_TOKEN=$(cat "$HOME/.hf_token")
fi

# Check GPU
nvidia-smi

# Run extraction
python grete/extraction/grete_extract_paper.py "$ARXIV_ID" --model "$MODEL_ID"

echo "=========================================="
echo "Completed: $ARXIV_ID with $MODEL_ID"
echo "=========================================="
