import os
import json
import argparse
import logging
import sys
from pathlib import Path
from dotenv import load_dotenv

# Add project root to path so we can find src
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.orkg_client import ORKGClient
from src.template_mapper import TemplateMapper
from src.orkg_manager import ORKGPaperManager

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("sandbox_uploader")

def main():
    parser = argparse.ArgumentParser(description="Upload extracted LLM data to ORKG Sandbox")
    parser.add_argument("--file", required=True, help="Path to the JSON file generated by Grete/Extraction")
    parser.add_argument("--host", default="sandbox", help="ORKG host (default: sandbox)")
    
    args = parser.parse_args()
    
    # 1. Load credentials
    load_dotenv()
    email = os.getenv("ORKG_EMAIL")
    password = os.getenv("ORKG_PASSWORD")
    
    if not email or not password:
        logger.error("Missing ORKG credentials. Please set ORKG_EMAIL and ORKG_PASSWORD in your .env file.")
        return

    # 2. Initialize components
    logger.info(f"Initializing ORKG components for {args.host}...")
    orkg_client = ORKGClient(host=args.host, email=email, password=password)
    template_mapper = TemplateMapper()
    manager = ORKGPaperManager(orkg_client, template_mapper)
    
    # 3. Load data
    try:
        with open(args.file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        logger.info(f"Loaded data from {args.file}")
    except Exception as e:
        logger.error(f"Failed to load JSON file: {e}")
        return

    # 4. Perform upload
    logger.info("Starting automated upload to ORKG...")
    
    # Construct paper_metadata if missing (Grete script saves flat structure)
    if "paper_metadata" not in data:
        data["paper_metadata"] = {
            "title": data.get("paper_title"),
            "arxiv_id": data.get("arxiv_id"),
            "url": f"https://arxiv.org/abs/{data.get('arxiv_id')}" if data.get("arxiv_id") else None,
            "authors": [] # Authors not currently preserved in simple JSON output
        }
        
    result = manager.process_and_upload(data)
    
    if result:
        print("\n" + "="*50)
        print("🚀 UPLOAD SUCCESSFUL!")
        print(f"📄 Paper ID: {result.get('paper_id')}")
        print(f"🧬 Contributions: {', '.join(result.get('contribution_ids', []))}")
        print("🔗 Check it out in the comparison: https://sandbox.orkg.org/comparison/R1364660")
        print("="*50 + "\n")
    else:
        print("\n" + "!"*50)
        print("❌ UPLOAD FAILED.")
        print("Check sandbox_uploader logs for details.")
        print("!"*50 + "\n")

if __name__ == "__main__":
    main()
